brew install atom
brew install docker
brew install maccy
brew install virtualbox
brew install postman
brew install obs
brew install firefox
brew install visual-studio-code
brew install dotnet-sdk
brew install mos
brew install zotero
brew install node@16
brew install texlive
brew install 1password
brew install airserver
brew install balenaetcher
brew install boop
brew install webex-meetings
brew install discord
brew install drawio
brew install jetbrains-toolbox
brew install sound-control
brew install the-unarchiver
